# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listresource',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_of_lists', to='resource.Resource'),
        ),
    ]
