# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0002_auto_20170531_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgreSQLDatabaseAccess',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource.Resource')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(default=secrets.token_urlsafe, max_length=200)),
                ('database', models.CharField(max_length=200)),
            ],
            bases=('resource.resource',),
        ),
        migrations.CreateModel(
            name='PostgreSQLServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('admin_user', models.CharField(max_length=200)),
                ('admin_password', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postgresqlserver',
            unique_together=set([('host', 'port')]),
        ),
        migrations.AddField(
            model_name='postgresqldatabaseaccess',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgresql.PostgreSQLServer'),
        ),
        migrations.AlterUniqueTogether(
            name='postgresqldatabaseaccess',
            unique_together=set([('server', 'user'), ('server', 'database')]),
        ),
    ]
